/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package user;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author icbt
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(this);
        

        
        String status = LoginStatus.status;
        
        
        if(status.equals("admin"))
        {
            mnuAbout.setEnabled(true);
            mnuChangePassword.setEnabled(true);
            mnuClose.setEnabled(true);
            mnuDeleteUser.setEnabled(true);
            mnuEvent.setEnabled(false);
            mnuLogout.setEnabled(true);
            mnuNewUser.setEnabled(true);
            mnuParticipant.setEnabled(false);
            mnuRegistration.setEnabled(false);
            mnuUserManual.setEnabled(true);
        }
        else if(status.equals("manager"))
        {
            mnuAbout.setEnabled(true);
            mnuChangePassword.setEnabled(false);
            mnuClose.setEnabled(true);
            mnuDeleteUser.setEnabled(false);
            mnuEvent.setEnabled(true);
            mnuLogout.setEnabled(true);
            mnuNewUser.setEnabled(false);
            mnuParticipant.setEnabled(true);
            mnuRegistration.setEnabled(true);
            mnuUserManual.setEnabled(true);
        }
        else if(status.equals("user"))
        {
            mnuAbout.setEnabled(true);
            mnuChangePassword.setEnabled(false);
            mnuClose.setEnabled(true);
            mnuDeleteUser.setEnabled(false);
            mnuEvent.setEnabled(false);
            mnuLogout.setEnabled(true);
            mnuNewUser.setEnabled(false);
            mnuParticipant.setEnabled(false);
            mnuRegistration.setEnabled(false);
            mnuUserManual.setEnabled(true);        
        }
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuEvent = new javax.swing.JMenuItem();
        mnuParticipant = new javax.swing.JMenuItem();
        mnuRegistration = new javax.swing.JMenuItem();
        mnuClose = new javax.swing.JMenuItem();
        mnuView = new javax.swing.JMenu();
        mnuViewEvents = new javax.swing.JCheckBoxMenuItem();
        mnuViewParticipants = new javax.swing.JCheckBoxMenuItem();
        mnuViewRegistrations = new javax.swing.JCheckBoxMenuItem();
        mnuLogin = new javax.swing.JMenu();
        mnuNewUser = new javax.swing.JMenuItem();
        mnuChangePassword = new javax.swing.JMenuItem();
        mnuDeleteUser = new javax.swing.JMenuItem();
        mnuLogout = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuUserManual = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nemico Cheque Printing System");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Cheque Printing System");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Welcome to Nemico ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Fashion Paradise's");

        mnuFile.setText("File");

        mnuEvent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mnuEvent.setText("Cheque");
        mnuEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEventActionPerformed(evt);
            }
        });
        mnuFile.add(mnuEvent);

        mnuParticipant.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnuParticipant.setText("Payee");
        mnuParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuParticipantActionPerformed(evt);
            }
        });
        mnuFile.add(mnuParticipant);

        mnuRegistration.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        mnuRegistration.setText("Registration");
        mnuRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrationActionPerformed(evt);
            }
        });
        mnuFile.add(mnuRegistration);

        mnuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuClose.setText("Close");
        mnuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCloseActionPerformed(evt);
            }
        });
        mnuFile.add(mnuClose);

        jMenuBar1.add(mnuFile);

        mnuView.setText("View");

        mnuViewEvents.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuViewEvents.setSelected(true);
        mnuViewEvents.setText("View Cheque Details");
        mnuViewEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewEventsActionPerformed(evt);
            }
        });
        mnuView.add(mnuViewEvents);

        mnuViewParticipants.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuViewParticipants.setSelected(true);
        mnuViewParticipants.setText("View Payee Details");
        mnuViewParticipants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewParticipantsActionPerformed(evt);
            }
        });
        mnuView.add(mnuViewParticipants);

        mnuViewRegistrations.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuViewRegistrations.setSelected(true);
        mnuViewRegistrations.setText("View Registrations");
        mnuViewRegistrations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewRegistrationsActionPerformed(evt);
            }
        });
        mnuView.add(mnuViewRegistrations);

        jMenuBar1.add(mnuView);

        mnuLogin.setText("Login");

        mnuNewUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        mnuNewUser.setText("New User");
        mnuNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewUserActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuNewUser);

        mnuChangePassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuChangePassword.setText("Change Password");
        mnuChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChangePasswordActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuChangePassword);

        mnuDeleteUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        mnuDeleteUser.setText("Delete User");
        mnuDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteUserActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuDeleteUser);

        mnuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        mnuLogout.setText("Logout");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuLogout);

        jMenuBar1.add(mnuLogin);

        mnuHelp.setText("Help");

        mnuUserManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnuUserManual.setText("User Manual");
        mnuUserManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUserManualActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuUserManual);

        mnuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuAbout);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuCloseActionPerformed

    private void mnuEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEventActionPerformed
        // TODO add your handling code here:
        ChequeForm ef=new ChequeForm();
        ef.setVisible(true);
    }//GEN-LAST:event_mnuEventActionPerformed

    private void mnuParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuParticipantActionPerformed
        // TODO add your handling code here:
        PayeeForm pf=new PayeeForm();
        pf.setVisible(true);
    }//GEN-LAST:event_mnuParticipantActionPerformed

    private void mnuRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrationActionPerformed
        // TODO add your handling code here:
        TransanctionForm rf = null;
        try {
            rf = new TransanctionForm();
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        rf.setVisible(true);
    }//GEN-LAST:event_mnuRegistrationActionPerformed

    private void mnuNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewUserActionPerformed
        // TODO add your handling code here:
        NewUserForm nuf=new NewUserForm();
        nuf.setVisible(true);
    }//GEN-LAST:event_mnuNewUserActionPerformed

    private void mnuChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChangePasswordActionPerformed
        // TODO add your handling code here:
        ChangePasswordForm cpf=new ChangePasswordForm();
        cpf.setVisible(true);
    }//GEN-LAST:event_mnuChangePasswordActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        // TODO add your handling code here:
        LoginForm lf=new LoginForm();
        lf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void mnuUserManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUserManualActionPerformed
        // TODO add your handling code here:
        try
        {
            Runtime.getRuntime().exec("Rundll32 url.dll, FileProtocolHandler "+"D:\\eventapp\\sample.pdf");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error");
         }
        
    }//GEN-LAST:event_mnuUserManualActionPerformed

    private void mnuDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteUserActionPerformed
        // TODO add your handling code here:
        DeleteUserForm duf=new DeleteUserForm();
        duf.setVisible(true);
    }//GEN-LAST:event_mnuDeleteUserActionPerformed

    private void mnuViewParticipantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewParticipantsActionPerformed
        // TODO add your handling code here:
        ViewPayeesForm vpf=new ViewPayeesForm();
        vpf.setVisible(true);
    }//GEN-LAST:event_mnuViewParticipantsActionPerformed

    private void mnuViewEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewEventsActionPerformed
        // TODO add your handling code here:
        ViewChequesForm vef=new ViewChequesForm();
        vef.setVisible(true);
    }//GEN-LAST:event_mnuViewEventsActionPerformed

    private void mnuViewRegistrationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewRegistrationsActionPerformed
        // TODO add your handling code here:
       ViewTransactionForm ref=new ViewTransactionForm();
        ref.setVisible(true);
    }//GEN-LAST:event_mnuViewRegistrationsActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        // TODO add your handling code here:
        try
        {
            Runtime.getRuntime().exec("Rundll32 url.dll, FileProtocolHandler "+"D:\\eventapp\\sample.pdf");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error");
         }
    }//GEN-LAST:event_mnuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenuItem mnuChangePassword;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JMenuItem mnuDeleteUser;
    private javax.swing.JMenuItem mnuEvent;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuLogin;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenuItem mnuNewUser;
    private javax.swing.JMenuItem mnuParticipant;
    private javax.swing.JMenuItem mnuRegistration;
    private javax.swing.JMenuItem mnuUserManual;
    private javax.swing.JMenu mnuView;
    private javax.swing.JCheckBoxMenuItem mnuViewEvents;
    private javax.swing.JCheckBoxMenuItem mnuViewParticipants;
    private javax.swing.JCheckBoxMenuItem mnuViewRegistrations;
    // End of variables declaration//GEN-END:variables
}
