/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package user;
import business.Cheque;
import data.ChequeDAO;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.sql.Date;
/**
 *
 * @author icbt
 */
public class ViewChequesForm extends javax.swing.JFrame {
private ChequeDAO edao;
private DefaultTableModel tblModel;
private ArrayList<Object> eventList;
    /**
     * Creates new form ViewEventsForm
     */
    public ViewChequesForm() {
        initComponents();
        edao= new ChequeDAO();
        tblModel = new DefaultTableModel();
        tblEvents.setModel(tblModel);
        tblModel.addColumn("Cheque ID");
        tblModel.addColumn("Bank Name");
        tblModel.addColumn("Cheque Date");
        tblModel.addColumn("Cheque Type");
        tblModel.addColumn("Payee");
        tblModel.addColumn("Description");
        tblModel.addColumn("Amount");
        
        eventList= edao.getAll();
        for(Object ob:eventList){
        Cheque ev= (Cheque)ob;
        int eID= ev.getEventID();
        String title=ev.getTitle();
        Date eDate=ev.geteDate();
        String time=ev.geteTime();
        String resPerson=ev.getResPerson();
        String contact=ev.getContact();
        double price=ev.getPrice();
        tblModel.addRow(new Object[]{eID,title,eDate,time,resPerson,contact,price});
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvents = new javax.swing.JTable();
        btnResource = new javax.swing.JButton();
        txtResource = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        txtTitle = new javax.swing.JTextField();
        btnTitle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEvents);

        btnResource.setText("Filter by Payee");
        btnResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResourceActionPerformed(evt);
            }
        });

        btnShow.setText("Show All");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnTitle.setText("Filter by Bank Name");
        btnTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtResource, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTitle))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResource))
                .addGap(18, 18, 18)
                .addComponent(btnShow)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResourceActionPerformed
        // TODO add your handling code here:
        String resPer = txtResource.getText();
        tblModel.setRowCount(0);
        for(Object ob:eventList){
        Cheque ev= (Cheque)ob;
        
        if(resPer.equals(ev.getResPerson()))
        {
        int eID= ev.getEventID();
        String title=ev.getTitle();
        Date eDate=ev.geteDate();
        String time=ev.geteTime();
        String resPerson=ev.getResPerson();
        String contact=ev.getContact();
        double price=ev.getPrice();
        tblModel.addRow(new Object[]{eID,title,eDate,time,resPerson,contact,price});
        }
        }
    }//GEN-LAST:event_btnResourceActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        tblModel.setRowCount(0);
       
        eventList=edao.getAll();
        
        for(Object ob:eventList){
        {
        Cheque ev= (Cheque)ob;
        int eID= ev.getEventID();
        String title=ev.getTitle();
        Date eDate=ev.geteDate();
        String time=ev.geteTime();
        String resPerson=ev.getResPerson();
        String contact=ev.getContact();
        double price=ev.getPrice();
        tblModel.addRow(new Object[]{eID,title,eDate,time,resPerson,contact,price});
        }
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitleActionPerformed
        // TODO add your handling code here:
        String etitle = txtTitle.getText();
        tblModel.setRowCount(0);
        for(Object ob:eventList){
        Cheque ev= (Cheque)ob;
        
        if(etitle.equals(ev.getTitle()))
        {
        int eID= ev.getEventID();
        String title=ev.getTitle();
        Date eDate=ev.geteDate();
        String time=ev.geteTime();
        String resPerson=ev.getResPerson();
        String contact=ev.getContact();
        double price=ev.getPrice();
        tblModel.addRow(new Object[]{eID,title,eDate,time,resPerson,contact,price});
        }
        }
    }//GEN-LAST:event_btnTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewChequesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewChequesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewChequesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewChequesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewChequesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResource;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEvents;
    private javax.swing.JTextField txtResource;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
