/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;
import business.Registration;
import data.TransactionDAO;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.sql.Date;
/**
 *
 * @author fshaz
 */
public class ViewTransactionForm extends javax.swing.JFrame {
private TransactionDAO rdao;
private DefaultTableModel tblModel;
private ArrayList<Object> rList;
    /**
     * Creates new form ViewRegistrationsForm
     */
    public ViewTransactionForm() {
        initComponents();
        rdao= new TransactionDAO();
        tblModel = new DefaultTableModel();
        tblRegistrations.setModel(tblModel);
        tblModel.addColumn("Transaction ID");
        tblModel.addColumn("Payee ID");
        tblModel.addColumn("Cheque ID");
        tblModel.addColumn("Transaction Date");
        tblModel.addColumn("Paid Status");
        
        rList= rdao.getAll();
        for(Object ob:rList){
        Registration r = (Registration)ob;
        int rID = r.getRegID();
        int pID= r.getpID();
        int eID = r.getEventID();
        Date rDate=r.getRegDate();
        String paid=r.getPaid();
       
        tblModel.addRow(new Object[]{rID, pID, eID, rDate, paid});
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistrations = new javax.swing.JTable();
        txtRID = new javax.swing.JTextField();
        btnRID = new javax.swing.JButton();
        txtPID = new javax.swing.JTextField();
        btnPID = new javax.swing.JButton();
        txtEID = new javax.swing.JTextField();
        btnEID = new javax.swing.JButton();
        txtP = new javax.swing.JTextField();
        btnP = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRegistrations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegistrations);

        btnRID.setText("Filter by Transaction ID");
        btnRID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRIDActionPerformed(evt);
            }
        });

        btnPID.setText("Filter by Payee ID");
        btnPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPIDActionPerformed(evt);
            }
        });

        btnEID.setText("Filter by Cheque No");
        btnEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEIDActionPerformed(evt);
            }
        });

        btnP.setText("Filter by Paid Status");
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });

        btnShow.setText("Show All");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtP)
                            .addComponent(txtEID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtRID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnRID, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPID, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnEID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShow)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRIDActionPerformed
        // TODO add your handling code here:
        String regi = txtRID.getText();
        tblModel.setRowCount(0);
        for(Object ob:rList){
        Registration r = (Registration)ob;
        
        if(regi.equals(r.getRegID()))
        {
        int rID = r.getRegID();
        int pID= r.getpID();
        int eID = r.getEventID();
        Date rDate=r.getRegDate();
        String paid=r.getPaid();
        tblModel.addRow(new Object[]{rID, pID, eID, rDate, paid});
        }
        }
    }//GEN-LAST:event_btnRIDActionPerformed

    private void btnPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPIDActionPerformed
        // TODO add your handling code here:
        String rpid = txtPID.getText();
        tblModel.setRowCount(0);
        for(Object ob:rList){
        Registration r = (Registration)ob;
        
        if(rpid.equals(r.getpID()))
        {
        int rID = r.getRegID();
        int pID= r.getpID();
        int eID = r.getEventID();
        Date rDate=r.getRegDate();
        String paid=r.getPaid();
        tblModel.addRow(new Object[]{rID, pID, eID, rDate, paid});
        }
        }
    }//GEN-LAST:event_btnPIDActionPerformed

    private void btnEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEIDActionPerformed
        // TODO add your handling code here:
        String reid = txtEID.getText();
        tblModel.setRowCount(0);
        for(Object ob:rList){
        Registration r = (Registration)ob;
        
        if(reid.equals(r.getEventID()))
        {
        int rID = r.getRegID();
        int pID= r.getpID();
        int eID = r.getEventID();
        Date rDate=r.getRegDate();
        String paid=r.getPaid();
        tblModel.addRow(new Object[]{rID, pID, eID, rDate, paid});
        }
        }
    }//GEN-LAST:event_btnEIDActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        // TODO add your handling code here:
        String rp = txtP.getText();
        tblModel.setRowCount(0);
        for(Object ob:rList){
        Registration r = (Registration)ob;
        
        if(rp.equals(r.getPaid()))
        {
        int rID = r.getRegID();
        int pID= r.getpID();
        int eID = r.getEventID();
        Date rDate=r.getRegDate();
        String paid=r.getPaid();
        tblModel.addRow(new Object[]{rID, pID, eID, rDate, paid});
        }
        }
    }//GEN-LAST:event_btnPActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        tblModel.setRowCount(0);
       
        rList=rdao.getAll();
        
        for(Object ob:rList){
        {
        Registration r= (Registration)ob;
         int rID = r.getRegID();
        int pID= r.getpID();
        int eID = r.getEventID();
        Date rDate=r.getRegDate();
        String paid=r.getPaid();
        tblModel.addRow(new Object[]{rID, pID, eID, rDate, paid});
        }
        }
    }//GEN-LAST:event_btnShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTransactionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEID;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnPID;
    private javax.swing.JButton btnRID;
    private javax.swing.JButton btnShow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistrations;
    private javax.swing.JTextField txtEID;
    private javax.swing.JTextField txtP;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtRID;
    // End of variables declaration//GEN-END:variables
}
